name: Test

on: [push, pull_request]

jobs:
  test:
    name: Test on ruby ${{ matrix.ruby_version }} and prawn ${{ matrix.prawn_version }}
    runs-on: ubuntu-latest
    # Run this build only on either pull request or push.
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    strategy:
      matrix:
        ruby_version:
          - '2.7'
          - '3.0'
          - '3.1'
          - '3.2'
        prawn_version:
          - '2.3'
          - '2.4'
        exclude:
          - ruby_version: '3.0'
            prawn_version: '2.3'
          - ruby_version: '3.1'
            prawn_version: '2.3'
          - ruby_version: '3.2'
            prawn_version: '2.3'

    steps:
    - uses: actions/checkout@v3

    - uses: hidakatsuya/setup-diff-pdf@v1
      with:
        diff-pdf-version: 0.5

    - name: Set up Ruby ${{ matrix.ruby_version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby_version }}

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install --gemfile gemfiles/prawn-${{ matrix.prawn_version }}.gemfile --jobs 4 --retry 3

    - name: Run Tests
      run: xvfb-run -a bundle exec rake test
